# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: <- Back
foot_title: Benjamin / Developer
email: benjsear9542@granitesd.org
description: > # this means to ignore newlines until "baseurl:"
    You can see my stats by clicking on the github link.  Questions, Comments, or Suggestions can go to the email provided.
baseurl: "" # the subpath of your site, e.g. /blog
url: "thegreatbenbino.github.io" # the base hostname & protocol for your site
github_username:  TheGreatBenbino

# Build settings
markdown: kramdown
